### ISSUE TITLE
not logging in

### ISSUE THREAD

**Issue by KaustubhRai** [hussaino03/QuestLog#71]
signing in with google does not work
browser - brave
device - m1 pro

video attached : 

https://github.com/user-attachments/assets/b521a362-c908-43d0-a807-ae5638e5b839

**Comment by hussaino03** [comment]
@KaustubhRai I initially thought that the issue was with CORS settings but after researching, turns out its related to the browser settings. Could you go into your browser settings, and choose "Allow all 3rd party cookies", and then try logging in? In general, for auth to flow, third-party cookies need to be enabled

**Comment by KaustubhRai** [comment]
yep works now. turns out, brave was blocking those 3rd party cookies.
